version: "3.7"

services:
  chat:
    build:
      context: ./src/services/chat
      dockerfile: Dockerfile
    container_name: vulcan-chat
    init: true
    restart: always
    depends_on:
      - user
    env_file:
      - ./src/services/chat/.env
  stream:
    build:
      context: ./src/services/stream
      dockerfile: Dockerfile
    container_name: vulcan-stream
    init: true
    restart: always
    env_file:
      - ./src/services/stream/.env
  user:
    build:
      context: ./src/services/user
      dockerfile: Dockerfile
    container_name: vulcan-user
    init: true
    restart: always
    env_file:
      - ./src/services/user/.env
