version: "3.7"

services:
  overlay:
    build:
      context: ./src/services/overlay
      dockerfile: Dockerfile
    container_name: vulcan-overlay
    init: true
    restart: always
    ports:
      - "3000:80"
    env_file:
      - ./src/services/overlay/.env
  chat:
    build:
      context: ./src/services/chat
      dockerfile: Dockerfile
    container_name: vulcan-chat
    init: true
    restart: always
    depends_on:
      - user
    env_file:
      - ./src/services/chat/.env
  logger:
    build:
      context: ./src/services/logger
      dockerfile: Dockerfile
    container_name: vulcan-logger
    init: true
    restart: always
    env_file:
      - ./src/services/logger/.env
  stream:
    build:
      context: ./src/services/stream
      dockerfile: Dockerfile
    container_name: vulcan-stream
    init: true
    restart: always
    env_file:
      - ./src/services/stream/.env
  streamelements:
    build:
      context: ./src/services/streamelements
      dockerfile: Dockerfile
    container_name: vulcan-streamelements
    init: true
    restart: always
    env_file:
      - ./src/services/streamelements/.env
  user:
    build:
      context: ./src/services/user
      dockerfile: Dockerfile
    container_name: vulcan-user
    init: true
    restart: always
    env_file:
      - ./src/services/user/.env
