version: "3.7"

services:
  chat:
    build:
      context: ./src/services/chat
      dockerfile: Dockerfile
    container_name: vulcan-chat
    init: true
    restart: always
    depends_on:
      - user
    env_file:
      - ./src/services/chat/.env
  overlay:
    build:
      context: ./src/services/overlay
      dockerfile: Dockerfile
    container_name: vulcan-overlay
    init: true
    restart: always
    ports:
      - "80:80"
    env_file:
      - ./src/services/overlay/.env
  user:
    image: vulcan.azurecr.io/vulcan-user:668
    container_name: vulcan-user
    init: true
    restart: always
    env_file:
      - ./src/services/user/.env
